# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\x1a\x1fgoogle/protobuf/timestamp.proto\"2\n\x0fRegisterRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"P\n\rRegisterReply\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12.\n\ncreated_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"/\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"6\n\nLoginReply\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x12\n\nexpires_in\x18\x02 \x01(\x03\"%\n\x14ValidateTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"7\n\x12ValidateTokenReply\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"\x1e\n\rLogoutRequest\x12\r\n\x05token\x18\x01 \x01(\t\"\x1d\n\x0bLogoutReply\x12\x0e\n\x06status\x18\x01 \x01(\t2\xf5\x01\n\x0b\x41uthService\x12\x38\n\x08Register\x12\x15.auth.RegisterRequest\x1a\x13.auth.RegisterReply\"\x00\x12/\n\x05Login\x12\x12.auth.LoginRequest\x1a\x10.auth.LoginReply\"\x00\x12G\n\rValidateToken\x12\x1a.auth.ValidateTokenRequest\x1a\x18.auth.ValidateTokenReply\"\x00\x12\x32\n\x06Logout\x12\x13.auth.LogoutRequest\x1a\x11.auth.LogoutReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=53
  _globals['_REGISTERREQUEST']._serialized_end=103
  _globals['_REGISTERREPLY']._serialized_start=105
  _globals['_REGISTERREPLY']._serialized_end=185
  _globals['_LOGINREQUEST']._serialized_start=187
  _globals['_LOGINREQUEST']._serialized_end=234
  _globals['_LOGINREPLY']._serialized_start=236
  _globals['_LOGINREPLY']._serialized_end=290
  _globals['_VALIDATETOKENREQUEST']._serialized_start=292
  _globals['_VALIDATETOKENREQUEST']._serialized_end=329
  _globals['_VALIDATETOKENREPLY']._serialized_start=331
  _globals['_VALIDATETOKENREPLY']._serialized_end=386
  _globals['_LOGOUTREQUEST']._serialized_start=388
  _globals['_LOGOUTREQUEST']._serialized_end=418
  _globals['_LOGOUTREPLY']._serialized_start=420
  _globals['_LOGOUTREPLY']._serialized_end=449
  _globals['_AUTHSERVICE']._serialized_start=452
  _globals['_AUTHSERVICE']._serialized_end=697
# @@protoc_insertion_point(module_scope)
